# Generated by Django 3.1.5 on 2021-01-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='data',
            field=models.DateField(auto_now=True, verbose_name='Data do Evento'),
        ),
    ]
