# Generated by Django 3.1.5 on 2021-01-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_auto_20210120_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='mercado',
            field=models.CharField(choices=[('ml', 'ML'), ('am', 'Ambas Marcam'), ('ov', 'Over'), ('un', 'Under'), ('mu', 'Múltipla'), ('ea', 'Empate Anula')], default='ml', max_length=10, verbose_name='Mercado'),
        ),
    ]
