# Generated by Django 3.1.5 on 2021-01-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_bet_mercado'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='lucro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Lucro'),
        ),
        migrations.AddField(
            model_name='bet',
            name='odd',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Odd'),
        ),
        migrations.AddField(
            model_name='bet',
            name='resultado',
            field=models.CharField(choices=[('g', 'Green'), ('r', 'Red'), ('d', 'Devolvida'), ('e', 'Encerrada')], default='g', max_length=10, verbose_name='Resultado da Aposta'),
        ),
        migrations.AddField(
            model_name='bet',
            name='valor_aposta',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Valor da Aposta'),
        ),
    ]
