# Generated by Django 3.1.5 on 2021-01-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_auto_20210120_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='roi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ROI'),
        ),
    ]
