# Generated by Django 3.1.5 on 2021-01-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0008_auto_20210121_1225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BetUpdate',
        ),
    ]
