# Generated by Django 3.1.5 on 2021-01-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0010_auto_20210121_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='editar_lucro',
            field=models.BooleanField(default=False, verbose_name='Editar Retorno'),
        ),
    ]
