# Generated by Django 3.1.5 on 2021-01-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0012_auto_20210121_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='lucro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Lucro'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='odd',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Odd'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='roi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ROI'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='valor_aposta',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Valor da Aposta'),
        ),
    ]
