# Generated by Django 3.1.5 on 2021-01-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0013_auto_20210121_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'ordering': ['-data']},
        ),
    ]
