# Generated by Django 3.1.5 on 2021-01-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0014_auto_20210121_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='resultado',
            field=models.CharField(choices=[('g', 'Green'), ('r', 'Red'), ('d', 'Devolvida'), ('e', 'Encerrada'), ('p', 'Pendente')], default='g', max_length=10, verbose_name='Resultado da Aposta'),
        ),
    ]
